# Generated by Django 4.2.7 on 2023-11-27 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('08:00', '08:00 - 10:00'), ('10:00', '10:00-12:00'), ('12:30', '12:30-14:30'), ('14:30', '14:30-16:30'), ('17:00', '17:00-19:00'), ('19:00', '19:00-21:00')], max_length=10)),
                ('capacity', models.IntegerField(default=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('INSTRUCTOR', 'Instructor'), ('GOVERNMENT', 'Government Official'), ('PUBLIC', 'General Public User')], default='PUBLIC', max_length=30)),
                ('badge_number', models.CharField(blank=True, max_length=5)),
                ('card_number', models.CharField(blank=True, max_length=4)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_events', models.ManyToManyField(blank=True, related_name='creators', to='community.event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.userprofile'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.event')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('CREATE_EVENT', ' Created Event'), ('JOIN_EVENT', ' Joined Event')], max_length=90)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.event')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_changes', to='community.userprofile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('date', 'time')},
        ),
    ]
