# Generated by Django 4.2.7 on 2023-11-15 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.CharField(choices=[('08:00', '08:00 - 10:00'), ('10:00', '10:00-12:00'), ('12:30', '12:30-14:30'), ('14:30', '14:30-16:30'), ('17:00', '17:00-19:00'), ('19:00', '19:00-21:00')], max_length=10)),
                ('end_time', models.CharField(choices=[('08:00', '08:00 - 10:00'), ('10:00', '10:00-12:00'), ('12:30', '12:30-14:30'), ('14:30', '14:30-16:30'), ('17:00', '17:00-19:00'), ('19:00', '19:00-21:00')], max_length=10)),
                ('capacity', models.IntegerField(default=60)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.event')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.userprofile')),
            ],
        ),
    ]
