# Generated by Django 4.2.7 on 2023-11-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_event_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_events',
            field=models.ManyToManyField(blank=True, related_name='creators', to='community.event'),
        ),
    ]
