# Generated by Django 4.2.7 on 2023-11-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('date', 'start_time')},
        ),
    ]
