# Generated by Django 4.2.7 on 2023-12-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_balancechange_staff_member_userprofile_staff_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='course_type',
            field=models.CharField(choices=[('free', 'Free'), ('instructor_led', 'Instructor-led')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, to='community.tag'),
        ),
    ]
