# Generated by Django 4.2.7 on 2023-12-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_tag_event_course_type_event_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='course_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, choices=[('education', 'Education'), ('physical_fitness', 'Physical Fitness'), ('wellbeing', 'Wellbeing'), ('technology', 'Technology'), ('art_culture', 'Art & Culture'), ('science_innovation', 'Science & Innovation'), ('environment', 'Environment'), ('entrepreneurship', 'Entrepreneurship'), ('community_service', 'Community Service'), ('personal_development', 'Personal Development'), ('health_nutrition', 'Health & Nutrition')], max_length=50),
        ),
    ]
