# Generated by Django 4.2.7 on 2023-12-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_remove_event_course_type_remove_event_tags_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('event', 'user_profile')},
        ),
    ]
