# Generated by Django 4.2.7 on 2023-11-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_balancechange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancechange',
            name='transaction_type',
            field=models.CharField(choices=[('CREATE_EVENT', ' Created Event'), ('JOIN_EVENT', ' Joined Event')], max_length=90),
        ),
    ]
