# Generated by Django 4.2.7 on 2023-11-22 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_alter_balancechange_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
    ]
