# Generated by Django 4.2.7 on 2023-11-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_remove_event_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='time',
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('date', 'time')},
        ),
    ]
