# Generated by Django 4.2.7 on 2023-11-22 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_rename_start_time_event_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cost',
        ),
    ]
